### ISSUE TITLE
Deref doesn't handle circular references properly

### ISSUE THREAD

**Issue by czardoz** [pateketrueke/deref#4]
This script reproduces the error:

``` javascript

var deref = require('deref');

var dereferencer = deref();

var schema = {
    "id": "http://json-schema.org/draft-04/schema#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "testProperty": {
            "$ref": "#"
        }
    }
};

dereferencer(schema, [], true);
```

Error:

```
/home/aniket/{removed}/node_modules/deref/lib/util/resolve-schema.js:10
  if (Array.isArray(obj)) {
            ^
RangeError: Maximum call stack size exceeded
    at Function.isArray (native)
    at clone (/home/aniket/git/collection-format-v2/node_modules/deref/lib/util/resolve-schema.js:10:13)
    at clone (/home/aniket/git/collection-format-v2/node_modules/deref/lib/util/resolve-schema.js:34:19)
    at clone (/home/aniket/git/collection-format-v2/node_modules/deref/lib/util/resolve-schema.js:34:19)
    at clone (/home/aniket/git/collection-format-v2/node_modules/deref/lib/util/resolve-schema.js:23:16)
    at clone (/home/aniket/git/collection-format-v2/node_modules/deref/lib/util/resolve-schema.js:34:19)
    at clone (/home/aniket/git/collection-format-v2/node_modules/deref/lib/util/resolve-schema.js:34:19)
    at clone (/home/aniket/git/collection-format-v2/node_modules/deref/lib/util/resolve-schema.js:23:16)
    at clone (/home/aniket/git/collection-format-v2/node_modules/deref/lib/util/resolve-schema.js:34:19)
    at clone (/home/aniket/git/collection-format-v2/node_modules/deref/lib/util/resolve-schema.js:34:19)

```

Ideally, the schema should not be changed at all (since it's a circular reference).

**Comment by pateketrueke** [comment]
Totally agree, actually i'm working on the `develop` branch to solve that. :calendar:

**Comment by czardoz** [comment]
Oh, that'll surely help me a lot. :cake: 

[Offtopic] I love the deref API. No other library actually allows users to pass in a list of schemas to be dereferenced. Thanks for this :)

**Comment by mitar** [comment]
I think this can be closed now, no?
